

---

**NUMPY**

---

## Introduction to NumPy

NumPy (Numerical Python) is a powerful, open-source library in Python, primarily used for numerical operations. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays. NumPy is a fundamental package for scientific computing in Python and is the backbone of many other data science libraries like Pandas and Scikit-learn.

## Common NumPy Functions

NumPy offers a vast array of functions for array manipulation, mathematical operations, and statistical analysis. Here are a few examples:

In [14]:
import numpy as np

# Create a sample array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)

# Basic statistical functions
print("\nMinimum element (overall):", np.min(arr))
print("Maximum element (overall):", np.max(arr))
print("Minimum element (per column):", np.min(arr, axis=0))
print("Maximum element (per row):", np.max(arr, axis=1))
print("Sum of all elements:", np.sum(arr))
print("Mean of all elements:", np.mean(arr))
print("Standard deviation of all elements:", np.std(arr))

# Array manipulation
print("\nTransposed Array:\n", np.transpose(arr))
print("Flattened Array:", arr.flatten())

# Element-wise operations
arr2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print("\nArray 1 + Array 2:\n", arr + arr2)
print("Array 1 x Array 2:\n", arr @ arr2)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Minimum element (overall): 1
Maximum element (overall): 9
Minimum element (per column): [1 2 3]
Maximum element (per row): [3 6 9]
Sum of all elements: 45
Mean of all elements: 5.0
Standard deviation of all elements: 2.581988897471611

Transposed Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Flattened Array: [1 2 3 4 5 6 7 8 9]

Array 1 + Array 2:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Array 1 x Array 2:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

In [2]:
# Question 1: How do you create a 1D NumPy array with values from 0 to 9?
import numpy as np

# Answer:
arr_1d = np.arange(10)
print(arr_1d)
print(f"Shape: {arr_1d.shape}, Dimension: {arr_1d.ndim}")

[0 1 2 3 4 5 6 7 8 9]
Shape: (10,), Dimension: 1

In [3]:
# Question 2: How do you create a 2D NumPy array (3x3) filled with ones?
import numpy as np

# Answer:
arr_ones = np.ones((3, 3))
print(arr_ones)
print(f"Shape: {arr_ones.shape}, Dimension: {arr_ones.ndim}")

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape: (3, 3), Dimension: 2

In [4]:
# Question 3: Given a 1D array, how would you convert it into a 2D array (2 rows, 5 columns)?
import numpy as np

# Answer:
arr_1d = np.arange(10)
arr_2d = arr_1d.reshape(2, 5)
print("Original 1D array:", arr_1d)
print("Reshaped 2D array:\n", arr_2d)
print(f"Shape: {arr_2d.shape}")

Original 1D array: [0 1 2 3 4 5 6 7 8 9]
Reshaped 2D array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Shape: (2, 5)

In [5]:
# Question 4: How do you perform element-wise addition of two NumPy arrays of the same shape?
import numpy as np

# Answer:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result_add = arr1 + arr2 # or np.add(arr1, arr2)
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Element-wise addition:\n", result_add)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Element-wise addition:
 [[ 6  8]
 [10 12]]

In [6]:
# Question 5: Explain NumPy broadcasting with an example where a scalar is added to an array.
import numpy as np

# Answer:
# Broadcasting allows NumPy to perform operations on arrays of different shapes.
# When a scalar is added to an array, the scalar is 'broadcast' across all elements of the array.

arr_orig = np.array([10, 20, 30])
scalar = 5

result_broadcast = arr_orig + scalar
print("Original array:", arr_orig)
print("Scalar:", scalar)
print("Array + Scalar (Broadcasting):", result_broadcast)

Original array: [10 20 30]
Scalar: 5
Array + Scalar (Broadcasting): [15 25 35]

In [7]:
# Question 6: How do you select the second row and the third column from a 2D NumPy array?
import numpy as np

# Answer:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Select the second row (index 1)
second_row = arr_2d[1, :]

# Select the third column (index 2)
third_column = arr_2d[:, 2]

print("Original 2D array:\n", arr_2d)
print("Second row:", second_row)
print("Third column:", third_column)

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row: [5 6 7 8]
Third column: [ 3  7 11]

In [8]:
# Question 7: Differentiate between a 'view' and a 'copy' in NumPy when slicing. Provide an example.
import numpy as np

# Answer:
# Slicing often creates a 'view' (a reference to the original data).
# Modifying a view *will* change the original array.
original_arr_view = np.array([1, 2, 3, 4, 5])
view_arr = original_arr_view[1:4]
view_arr[0] = 99
print("Original array after view modification:", original_arr_view)

# To explicitly create a 'copy' (independent data),
# use the .copy() method.
# Modifying a copy *will NOT* change the original array.
original_arr_copy = np.array([10, 20, 30, 40, 50])
copy_arr = original_arr_copy[1:4].copy()
copy_arr[0] = 999
print("Original array after copy modification:", original_arr_copy)
print("Copied slice:", copy_arr)

Original array after view modification: [ 1 99  3  4  5]
Original array after copy modification: [10 20 30 40 50]
Copied slice: [999  30  40]

In [9]:
# Question 8: How do you filter elements in a NumPy array based on a condition (Boolean indexing)?
import numpy as np

# Answer:
my_array = np.array([1, 5, 8, 12, 15, 20, 22])

# Condition: select elements greater than 10
condition = my_array > 10
filtered_array = my_array[condition]

print("Original array:", my_array)
print("Condition (my_array > 10):", condition)
print("Filtered array (elements > 10):", filtered_array)

Original array: [ 1  5  8 12 15 20 22]
Condition (my_array > 10): [False False False  True  True  True  True]
Filtered array (elements > 10): [12 15 20 22]

In [10]:
# Question 9: How can you check the data type (dtype) of a NumPy array and change it?
import numpy as np

# Answer:
arr_int = np.array([1, 2, 3])
print(f"Initial array: {arr_int}, Dtype: {arr_int.dtype}")

# Change dtype to float
arr_float = arr_int.astype(np.float64)
print(f"Array after changing to float: {arr_float}, Dtype: {arr_float.dtype}")

# Change dtype to string
arr_str = arr_int.astype(str)
print(f"Array after changing to string: {arr_str}, Dtype: {arr_str.dtype}")

Initial array: [1 2 3], Dtype: int64
Array after changing to float: [1. 2. 3.], Dtype: float64
Array after changing to string: ['1' '2' '3'], Dtype: <U21

In [11]:
# Question 10: How do you concatenate two NumPy arrays both horizontally and vertically?
import numpy as np

# Answer:
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])

# Horizontal concatenation (stacking column-wise)
h_stack = np.hstack((arr_a, arr_b))
# Alternative: np.concatenate((arr_a, arr_b), axis=1)

# Vertical concatenation (stacking row-wise)
v_stack = np.vstack((arr_a, arr_b))
# Alternative: np.concatenate((arr_a, arr_b), axis=0)

print("Array A:\n", arr_a)
print("Array B:\n", arr_b)
print("Horizontal Stack:\n", h_stack)
print("Vertical Stack:\n", v_stack)

Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

In [12]:
# Question 11: How do you rotate a 2D NumPy matrix 90 degrees clockwise?
import numpy as np

# Answer:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# np.rot90 rotates counter-clockwise by default. To rotate clockwise,
# we can either rotate three times counter-clockwise (k=3) or
# rotate once counter-clockwise (k=1) and then flip left/right or up/down.
# The simplest is to use k=-1 for 90 degrees clockwise rotation.

rotated_matrix_clockwise = np.rot90(matrix, k=-1)

print("Original Matrix:\n", matrix)
print("Rotated 90 degrees clockwise:\n", rotated_matrix_clockwise)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rotated 90 degrees clockwise:
 [[7 4 1]
 [8 5 2]
 [9 6 3]]



---

**PANDAS**

---

## Introduction to Pandas

Pandas is a fast, powerful, flexible, and easy-to-use open-source data analysis and manipulation tool, built on top of the Python programming language. It is a fundamental library for data science in Python, providing data structures like DataFrames and Series, which are designed to work with tabular data, similar to spreadsheets or SQL tables. Pandas excels at handling, cleaning, exploring, and manipulating data, making it an indispensable tool for data professionals.

## Common Pandas Functions

Pandas provides two primary data structures: **Series** (a one-dimensional labeled array) and **DataFrame** (a two-dimensional labeled data structure with columns of potentially different types). Here are some common operations and functions:

In [15]:
import pandas as pd
import numpy as np

# 1. Creating Series and DataFrames
print("--- Creating Series and DataFrames ---")
# From a list
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print("Series:\n", s)

# From a dictionary (DataFrame)
data = {'col1': [1, 2, 3, 4], 'col2': [4, 3, 2, 1]}
df_from_dict = pd.DataFrame(data)
print("DataFrame from dictionary:\n", df_from_dict)

# From a NumPy array
dates = pd.date_range('20230101', periods=6)
df_from_numpy = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print("DataFrame from NumPy array:\n", df_from_numpy)

--- Creating Series and DataFrames ---
Series:
 0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
DataFrame from dictionary:
    col1  col2
0     1     4
1     2     3
2     3     2
3     4     1
DataFrame from NumPy array:
                    A         B         C         D
2023-01-01  0.736182 -0.117730 -0.663670  0.983714
2023-01-02 -1.068294  3.146530  1.005322 -0.138463
2023-01-03  0.174128  0.510946 -1.801540 -0.373835
2023-01-04 -0.852206 -0.070681  0.870803  0.808419
2023-01-05  1.122031  0.456742 -2.278322  0.180732
2023-01-06  0.102685 -0.223086 -0.535966  0.059054

In [16]:
import pandas as pd
import numpy as np

# Let's create a sample DataFrame for demonstration
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Age': [25, 30, 35, 28, 22, 40, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'New York', 'Los Angeles'],
    'Salary': [70000, 85000, 100000, 60000, 55000, 110000, 90000],
    'Experience': [2, 7, 10, 3, 1, 15, 6],
    'Department': ['HR', 'Engineering', 'Sales', 'HR', 'Marketing', 'Engineering', 'Sales'],
    'Rating': [4.5, 3.8, 4.9, np.nan, 4.1, 4.7, 3.5]
}
df = pd.DataFrame(data)

print("--- Data Inspection ---")
print("First 5 rows (df.head()):\n", df.head())
print("\nLast 3 rows (df.tail(3)):\n", df.tail(3))
print("\nDataFrame Info (df.info()):")
df.info()
print("\nDescriptive statistics (df.describe()):\n", df.describe())
print("\nColumn names (df.columns):", df.columns)
print("\nIndex (df.index):", df.index)
print("\nValues (df.values):\n", df.values)

print("\n--- Selection and Slicing ---")
print("Select 'Name' column:\n", df['Name'])
print("\nSelect 'Name' and 'Age' columns:\n", df[['Name', 'Age']])
print("\nSelect first two rows by position (iloc):\n", df.iloc[0:2])
print("\nSelect rows with Age > 30 and 'Engineering' Department:\n", df[(df['Age'] > 30) & (df['Department'] == 'Engineering')])

print("\n--- Missing Data Handling ---")
print("DataFrame with NaN values:\n", df)
print("\nCheck for NaN (df.isnull().sum()):\n", df.isnull().sum())
print("\nDrop rows with any NaN (df.dropna()):\n", df.dropna())
print("\nFill NaN with mean of 'Rating' (df.fillna(df['Rating'].mean())):\n", df['Rating'].fillna(df['Rating'].mean()))

print("\n--- Grouping and Aggregation ---")
print("Group by 'Department' and get mean 'Salary':\n", df.groupby('Department')['Salary'].mean())
print("\nGroup by 'City' and count 'Name':\n", df.groupby('City')['Name'].count())

print("\n--- Sorting ---")
print("Sort by 'Age' descending:\n", df.sort_values(by='Age', ascending=False))

print("\n--- Applying Functions ---")
# Apply a lambda function to create a new column
df['Salary_USD'] = df['Salary'].apply(lambda x: f"${x/1000:.0f}K")
print("DataFrame with 'Salary_USD':\n", df)

--- Data Inspection ---
First 5 rows (df.head()):
       Name  Age         City  Salary  Experience   Department  Rating
0    Alice   25     New York   70000           2           HR     4.5
1      Bob   30  Los Angeles   85000           7  Engineering     3.8
2  Charlie   35      Chicago  100000          10        Sales     4.9
3    David   28      Houston   60000           3           HR     NaN
4      Eve   22      Phoenix   55000           1    Marketing     4.1

Last 3 rows (df.tail(3)):
     Name  Age         City  Salary  Experience   Department  Rating
4    Eve   22      Phoenix   55000           1    Marketing     4.1
5  Frank   40     New York  110000          15  Engineering     4.7
6  Grace   32  Los Angeles   90000           6        Sales     3.5

DataFrame Info (df.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        7 non-null      object
 1   Age         7 non-null      int64
 2   City        7 non-null      object
 3   Salary      7 non-null      int64
 4   Experience  7 non-null      int64
 5   Department  7 non-null      object
 6   Rating      6 non-null      float64
dtypes: float64(1), int64(3), object(3)
memory usage: 524.0+ bytes

Descriptive statistics (df.describe()):
              Age         Salary  Experience    Rating
count   7.000000       7.000000    7.000000  6.000000
mean   30.285714   81428.571429    6.285714  4.250000
std     6.074929   20557.700446    4.956958  0.543139
min    22.000000   55000.000000    1.000000  3.500000
25%    26.500000   65000.000000    2.500000  3.875000
50%    30.000000   85000.000000    6.000000  4.300000
75%    33.500000   95000.000000    8.500000  4.650000
max    40.000000  110000.000000   15.000000  4.900000

Column names (df.columns): Index(['Name', 'Age', 'City', 'Salary', 'Experience', 'Department', 'Rating'], dtype='object')

Index (df.index): RangeIndex(start=0, stop=7, step=1)

Values (df.values):
 [['Alice' 25 'New York' 70000 2 'HR' 4.5]
 ['Bob' 30 'Los Angeles' 85000 7 'Engineering' 3.8]
 ['Charlie' 35 'Chicago' 100000 10 'Sales' 4.9]
 ['David' 28 'Houston' 60000 3 'HR' nan]
 ['Eve' 22 'Phoenix' 55000 1 'Marketing' 4.1]
 ['Frank' 40 'New York' 110000 15 'Engineering' 4.7]
 ['Grace' 32 'Los Angeles' 90000 6 'Sales' 3.5]]

--- Selection and Slicing ---
Select 'Name' column:
 0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
6      Grace
Name: Name, dtype: object

Select 'Name' and 'Age' columns:
       Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28
4      Eve   22
5    Frank   40
6    Grace   32

Select first two rows by position (iloc):
     Name  Age         City  Salary  Experience   Department  Rating
0  Alice   25     New York   70000           2           HR     4.5
1    Bob   30  Los Angeles   85000           7  Engineering     3.8

Select rows with Age > 30 and 'Engineering' Department:
     Name  Age      City  Salary  Experience   Department  Rating
5  Frank   40  New York  110000          15  Engineering     4.7

--- Missing Data Handling ---
DataFrame with NaN values:
       Name  Age         City  Salary  Experience   Department  Rating
0    Alice   25     New York   70000           2           HR     4.5
1      Bob   30  Los Angeles   85000           7  Engineering     3.8
2  Charlie   35      Chicago  100000          10        Sales     4.9
3    David   28      Houston   60000           3           HR     NaN
4      Eve   22      Phoenix   55000           1    Marketing     4.1
5    Frank   40     New York  110000          15  Engineering     4.7
6    Grace   32  Los Angeles   90000           6        Sales     3.5

Check for NaN (df.isnull().sum()):
 Name          0
Age           0
City          0
Salary        0
Experience    0
Department    0
Rating        1
dtype: int64

Drop rows with any NaN (df.dropna()):
       Name  Age         City  Salary  Experience   Department  Rating
0    Alice   25     New York   70000           2           HR     4.5
1      Bob   30  Los Angeles   85000           7  Engineering     3.8
2  Charlie   35      Chicago  100000          10        Sales     4.9
4      Eve   22      Phoenix   55000           1    Marketing     4.1
5    Frank   40     New York  110000          15  Engineering     4.7
6    Grace   32  Los Angeles   90000           6        Sales     3.5

Fill NaN with mean of 'Rating' (df.fillna(df['Rating'].mean())):
 0    4.50
1    3.80
2    4.90
3    4.25
4    4.10
5    4.70
6    3.50
Name: Rating, dtype: float64

--- Grouping and Aggregation ---
Group by 'Department' and get mean 'Salary':
 Department
Engineering    97500.0
HR             65000.0
Marketing      55000.0
Sales          95000.0
Name: Salary, dtype: float64

Group by 'City' and count 'Name':
 City
Chicago        1
Houston        1
Los Angeles    2
New York       2
Phoenix        1
Name: Name, dtype: int64

--- Sorting ---
Sort by 'Age' descending:
       Name  Age         City  Salary  Experience   Department  Rating
5    Frank   40     New York  110000          15  Engineering     4.7
2  Charlie   35      Chicago  100000          10        Sales     4.9
6    Grace   32  Los Angeles   90000           6        Sales     3.5
1      Bob   30  Los Angeles   85000           7  Engineering     3.8
3    David   28      Houston   60000           3           HR     NaN
0    Alice   25     New York   70000           2           HR     4.5
4      Eve   22      Phoenix   55000           1    Marketing     4.1

--- Applying Functions ---
DataFrame with 'Salary_USD':
       Name  Age         City  Salary  Experience   Department  Rating  \
0    Alice   25     New York   70000           2           HR     4.5
1      Bob   30  Los Angeles   85000           7  Engineering     3.8
2  Charlie   35      Chicago  100000          10        Sales     4.9
3    David   28      Houston   60000           3           HR     NaN
4      Eve   22      Phoenix   55000           1    Marketing     4.1
5    Frank   40     New York  110000          15  Engineering     4.7
6    Grace   32  Los Angeles   90000           6        Sales     3.5

  Salary_USD
0       $70K
1       $85K
2      $100K
3       $60K
4       $55K
5      $110K
6       $90K

In [19]:
# Question: Given a DataFrame containing employee details, find the average salary of employees in each department,
# but only include departments where the average age of employees is greater than 28.
# Finally, sort the resulting departments by their average salary in descending order.

import pandas as pd
import numpy as np

# Sample Dataset
data = {
    'Employee_ID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Henry'],
    'Department': ['HR', 'Engineering', 'Sales', 'HR', 'Engineering', 'Sales', 'HR', 'Engineering'],
    'Age': [25, 30, 35, 24, 22, 40, 31, 29],
    'Salary': [60000, 85000, 95000, 55000, 62000, 110000, 67000, 90000]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Answer:
# Step 1: Group by 'Department' and aggregate both mean 'Age' and mean 'Salary'
grouped = df.groupby('Department').agg(
    avg_age=('Age', 'mean'),
    avg_salary=('Salary', 'mean')
).reset_index()

# Step 2: Filter departments where average age > 28
filtered_depts = grouped[grouped['avg_age'] > 28]

# Step 3: Sort by average salary in descending order
result = filtered_depts.sort_values(by='avg_salary', ascending=False)

print("\nProcessed Result (Departments with average age > 28, sorted by average salary descending):\n", result)

Original DataFrame:
    Employee_ID     Name   Department  Age  Salary
0            1    Alice           HR   25   60000
1            2      Bob  Engineering   30   85000
2            3  Charlie        Sales   35   95000
3            4    David           HR   24   55000
4            5      Eve  Engineering   22   62000
5            6    Frank        Sales   40  110000
6            7    Grace           HR   31   67000
7            8    Henry  Engineering   29   90000

Processed Result (Departments with average age > 28, sorted by average salary descending):
   Department  avg_age  avg_salary
2      Sales     37.5    102500.0

In [20]:
# Question 1: How do you perform an inner join and a left join between two DataFrames on a specific key column?
import pandas as pd

# Sample Datasets
df_users = pd.DataFrame({
    'user_id': [1, 2, 3, 4],
    'username': ['alice', 'bob', 'charlie', 'david']
})

df_orders = pd.DataFrame({
    'order_id': [101, 102, 103],
    'user_id': [1, 2, 5], # user_id 5 does not exist in df_users, user_id 3 & 4 have no orders
    'amount': [250, 450, 150]
})

# Answer:
# Inner Join
inner_joined = pd.merge(df_users, df_orders, on='user_id', how='inner')
print("--- Inner Joined DataFrame ---")
display(inner_joined)

# Left Join
left_joined = pd.merge(df_users, df_orders, on='user_id', how='left')
print("\n--- Left Joined DataFrame ---")
display(left_joined)

--- Inner Joined DataFrame ---

   user_id username  order_id  amount
0        1    alice       101     250
1        2      bob       102     450

--- Left Joined DataFrame ---

   user_id username  order_id  amount
0        1    alice     101.0   250.0
1        2      bob     102.0   450.0
2        3  charlie       NaN     NaN
3        4    david       NaN     NaN

In [21]:
# Question 2: How do you find and remove duplicate rows in a DataFrame based on specific columns (e.g., 'email') while keeping the first occurrence?
import pandas as pd

# Sample Dataset
data = {
    'name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'email': ['alice@test.com', 'bob@test.com', 'alice@test.com', 'charlie@test.com', 'bob@test.com'],
    'signup_date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05']
}
df_users = pd.DataFrame(data)
print("Original DataFrame with duplicates:")
display(df_users)

# Answer:
# 1. Identify which rows are duplicates based on the 'email' column
duplicates = df_users.duplicated(subset=['email'], keep='first')
print("\nIs duplicate (True represents a duplicate that will be dropped):\n", duplicates)

# 2. Drop duplicates, keeping the first occurrence
clean_df = df_users.drop_duplicates(subset=['email'], keep='first')
print("\nCleaned DataFrame (duplicates removed):")
display(clean_df)

Original DataFrame with duplicates:

      name             email signup_date
0    Alice    alice@test.com  2023-01-01
1      Bob      bob@test.com  2023-01-02
2    Alice    alice@test.com  2023-01-03
3  Charlie  charlie@test.com  2023-01-04
4      Bob      bob@test.com  2023-01-05

Is duplicate (True represents a duplicate that will be dropped):
 0    False
1    False
2     True
3    False
4     True
dtype: bool

Cleaned DataFrame (duplicates removed):

      name             email signup_date
0    Alice    alice@test.com  2023-01-01
1      Bob      bob@test.com  2023-01-02
3  Charlie  charlie@test.com  2023-01-04

In [22]:
# Question 3: How do you filter a DataFrame using complex conditions (e.g., selecting rows where one column value is above a threshold, AND another column value matches a specific string)?
import pandas as pd

# Sample Dataset
data = {
    'item': ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard', 'Laptop'],
    'category': ['Electronics', 'Electronics', 'Electronics', 'Accessories', 'Accessories', 'Electronics'],
    'price': [1200, 800, 300, 150, 80, 1500],
    'in_stock': [True, False, True, True, False, True]
}
df_store = pd.DataFrame(data)
print("Original Inventory:")
display(df_store)

# Answer:
# Condition: Category is 'Electronics' AND price is greater than 500 AND it is in_stock
condition = (df_store['category'] == 'Electronics') & (df_store['price'] > 500) & (df_store['in_stock'] == True)

filtered_products = df_store[condition]
print("\nFiltered Products (In-stock Electronics > $500):")
display(filtered_products)

Original Inventory:

       item     category  price  in_stock
0    Laptop  Electronics   1200      True
1     Phone  Electronics    800     False
2    Tablet  Electronics    300      True
3   Monitor  Accessories    150      True
4  Keyboard  Accessories     80     False
5    Laptop  Electronics   1500      True

Filtered Products (In-stock Electronics > $500):

     item     category  price  in_stock
0  Laptop  Electronics   1200      True
5  Laptop  Electronics   1500      True

In [23]:
# Question 4: How can you optimize memory usage of a DataFrame containing high-cardinality object types and numeric columns by casting to optimized datatypes (like category and smaller integer representations)?
import pandas as pd
import numpy as np

# Sample Dataset
df_large = pd.DataFrame({
    'id': np.arange(1, 10001),
    'priority': np.random.choice(['Low', 'Medium', 'High'], size=10000),
    'score': np.random.randint(1, 100, size=10000)
})

print("--- Memory usage BEFORE optimization ---")
print(df_large.info(memory_usage='deep'))

# Answer:
# 1. Cast string objects with low cardinality to 'category'
df_large['priority'] = df_large['priority'].astype('category')

# 2. Downcast integers to smaller matching types (like int16 since max value is 10000)
df_large['id'] = pd.to_numeric(df_large['id'], downcast='unsigned')
df_large['score'] = pd.to_numeric(df_large['score'], downcast='unsigned')

print("\n--- Memory usage AFTER optimization ---")
print(df_large.info(memory_usage='deep'))

--- Memory usage BEFORE optimization ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        10000 non-null  int64
 1   priority  10000 non-null  object
 2   score     10000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 677.1 KB
None

--- Memory usage AFTER optimization ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        10000 non-null  uint16
 1   priority  10000 non-null  category
 2   score     10000 non-null  uint8
dtypes: category(1), uint16(1), uint8(1)
memory usage: 39.5 KB
None

In [24]:
# Question 5: Given daily stock prices, how do you compute the 7-day rolling average and resample the daily data into weekly averages?
import pandas as pd
import numpy as np

# Generating daily date-range and dummy prices
dates = pd.date_range(start='2023-01-01', end='2023-01-31', freq='D')
prices = np.random.normal(loc=100, scale=10, size=len(dates)).cumsum()
df_stocks = pd.DataFrame({'Price': prices}, index=dates)
print("First 5 days of daily prices:")
display(df_stocks.head())

# Answer:
# 1. Compute 7-day rolling average
df_stocks['7D_Rolling_Avg'] = df_stocks['Price'].rolling(window=7).mean()
print("\nDataFrame with 7-day rolling average:")
display(df_stocks.head(10)) # first few will be NaN because they need 7 previous data points

# 2. Resample daily data to weekly average
df_weekly = df_stocks['Price'].resample('W').mean().to_frame(name='Weekly_Avg_Price')
print("\nResampled Weekly Average Prices:")
display(df_weekly)

First 5 days of daily prices:

                 Price
2023-01-01  111.486856
2023-01-02  203.279692
2023-01-03  306.541628
2023-01-04  408.273410
2023-01-05  504.513583

DataFrame with 7-day rolling average:

                  Price  7D_Rolling_Avg
2023-01-01   111.486856             NaN
2023-01-02   203.279692             NaN
2023-01-03   306.541628             NaN
2023-01-04   408.273410             NaN
2023-01-05   504.513583             NaN
2023-01-06   592.466667             NaN
2023-01-07   691.687563      402.607057
2023-01-08   801.586282      501.192689
2023-01-09   906.502706      601.653120
2023-01-10  1012.830171      702.551483

Resampled Weekly Average Prices:

            Weekly_Avg_Price
2023-01-01        111.486856
2023-01-08        501.192689
2023-01-15       1197.552733
2023-01-22       1877.635482
2023-01-29       2579.442576
2023-02-05       3016.725625

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.